# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-19 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0025_auto_20180829_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
